apiVersion: v1
entries:
  sap-classes:
  - apiVersion: v2
    appVersion: latest
    created: "2026-08-27T05:00:23.372497613Z"
    description: A Helm chart for deploying the sap-classes frontend application
    digest: 1bd378fbdea22ecbdd3a123e699f37b1ad6503a900deca5836cb337de0112f61
    name: sap-classes
    type: application
    urls:
    - https://gauritambe.github.io/helm-chart-sap-classes/charts/sap-classes-0.1.0.tgz
    version: 0.1.0
generated: "2026-08-27T05:00:23.371713616Z"
